services:
  postgres:
    image: postgres:16
    container_name: task-manager-postgres
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB?err}
      POSTGRES_USER: ${POSTGRES_USER?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?err}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: task-manager-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    container_name: task-manager-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173

volumes:
  pgdata:
