services:
  postgres:
    image: postgres:16
    container_name: task-manager-postgres
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB?err}
      POSTGRES_USER: ${POSTGRES_USER?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?err}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER?err} -d ${POSTGRES_DB?err}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
